language: php
script: phpunit -c tests/phpunit.xml --verbose --coverage-text tests/

php:
  - 5.3
  - 5.4

before_script:
  - "composer install -v"

after_script:
  - "phpunit -c tests/phpunit.xml --testdox tests/"